
# - name: Setup tmate session
#   if: failure()
#   uses: mxschmitt/action-tmate@v3

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_build:
    name: Linux build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libasound2-dev 
        version: 1.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm i
    - name: npm run build sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm run build
    - name: npm i sampler-editor-librarian-client-angular
      working-directory: ./modules/sampler-editor-librarian-client-angular
      run: npm i
    - name: npm run build sampler-editor-librarian-client-angular
      working-directory: ./modules/sampler-editor-librarian-client-angular
      run: npm run build
    - name: npm i react-dial-knob
      working-directory: ./modules/react-dial-knob
      run: npm --force i
    - name: npm run build react-dial-knob
      working-directory: ./modules/react-dial-knob
      run: npm run build
    - name: npm i sampler-editor-librarian-client-react
      working-directory: ./modules/sampler-editor-librarian-client-react
      run: npm i
    - name: npm run build sampler-editor-librarian-client-react
      working-directory: ./modules/sampler-editor-librarian-client-react
      run: npm run build
    - name: npm i sampler-editor-librarian
      run: npm i
    - name: Copy angular ui type file to code base
      run: cp ./ui-type-angular ./src/ui-type.ts
    - name: npm run build-release sampler-editor-librarian angular
      run: npm run build-release
    - name: npm install -g pkg
      run: npm install -g pkg
    - name: pkg --debug -c ./pkg-angular.json -o sampler-editor-librarian-angular ./dist/main.js
      run: pkg --debug -c ./pkg-angular.json -o sampler-editor-librarian-angular ./dist/main.js
    - name: 'Upload Linux Angular Artifcat'
      uses: actions/upload-artifact@v4
      with:
        name: sampler-editor-librarian-angular-linux
        path: ./sampler-editor-librarian-angular-linux
    - name: Copy react ui type file to code base
      run: cp ./ui-type-react ./src/ui-type.ts
    - name: npm run build-release sampler-editor-librarian react
      run: npm run build-release
    - name: pkg --debug -c ./pkg-react.json -o sampler-editor-librarian-react ./dist/main.js
      run: pkg --debug -c ./pkg-react.json -o sampler-editor-librarian-react ./dist/main.js
    - name: 'Upload Linux React Artifcat'
      uses: actions/upload-artifact@v4
      with:
        name: sampler-editor-librarian-react-linux
        path: ./sampler-editor-librarian-react-linux
        
  windows_build:
    name: Windows build

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm i
    - name: npm run build sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm run build
    - name: npm i sampler-editor-librarian-client-angular
      working-directory: ./modules/sampler-editor-librarian-client-angular
      run: npm i
    - name: npm run build sampler-editor-librarian-client-angular
      working-directory: ./modules/sampler-editor-librarian-client-angular
      run: npm run build
    - name: npm i react-dial-knob
      working-directory: ./modules/react-dial-knob
      run: npm --force i
    - name: npm run build react-dial-knob
      working-directory: ./modules/react-dial-knob
      run: npm run build
    - name: npm i sampler-editor-librarian-client-react
      working-directory: ./modules/sampler-editor-librarian-client-react
      run: npm i
    - name: npm run build sampler-editor-librarian-client-react
      working-directory: ./modules/sampler-editor-librarian-client-react
      run: npm run build
    - name: npm i sampler-editor-librarian
      run: npm i
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Install nestjs CLI
      run: npm i -g @nestjs/cli
    - name: Copy angular ui type file to code base
      run: copy /y .\ui-type-angular .\src\ui-type.ts
    - name: nest build sampler-editor-librarian angular
      run: nest build
    - name: npm run neon:build -- --release
      run: npm run neon:build -- --release
    - name: npm install -g pkg
      run: npm install -g pkg
    - name: pkg --debug -c ./pkg-angular.json -o sampler-editor-librarian-angular ./dist/main.js
      run: pkg --debug -c ./pkg-angular.json -o sampler-editor-librarian-angular ./dist/main.js
    - name: 'Upload Windows Angularv Artifcat'
      uses: actions/upload-artifact@v4
      with:
        name: sampler-editor-librarian-angular-win.exe
        path: ./sampler-editor-librarian-angular-win.exe
    - name: Copy react ui type file to code base
      run: copy /y .\ui-type-react .\src\ui-type.ts
    - name: npm run build-release sampler-editor-librarian react
      run: npm run build-release
    - name: pkg --debug -c ./pkg-react.json -o sampler-editor-librarian-react ./dist/main.js
      run: pkg --debug -c ./pkg-react.json -o sampler-editor-librarian-react ./dist/main.js
    - name: 'Upload Windows React Artifcat'
      uses: actions/upload-artifact@v4
      with:
        name: sampler-editor-librarian-react-win.exe
        path: ./sampler-editor-librarian-react-win.exe

        
  macos_build:
    name: Mac OS build

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm i
    - name: npm run build sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm run build
    - name: npm i sampler-editor-librarian-client-angular
      working-directory: ./modules/sampler-editor-librarian-client-angular
      run: npm i
    - name: npm run build sampler-editor-librarian-client-angular
      working-directory: ./modules/sampler-editor-librarian-client-angular
      run: npm run build
    - name: npm i react-dial-knob
      working-directory: ./modules/react-dial-knob
      run: npm --force i
    - name: npm run build react-dial-knob
      working-directory: ./modules/react-dial-knob
      run: npm run build
    - name: npm i sampler-editor-librarian-client-react
      working-directory: ./modules/sampler-editor-librarian-client-react
      run: npm i
    - name: npm run build sampler-editor-librarian-client-react
      working-directory: ./modules/sampler-editor-librarian-client-react
      run: npm run build
    - name: npm i sampler-editor-librarian
      run: npm i
    - name: Copy angular ui type file to code base
      run: cp ./ui-type-angular ./src/ui-type.ts
    - name: npm run build-release sampler-editor-librarian angular
      run: npm run build-release
    - name: npm install -g pkg
      run: npm install -g pkg 
    - name: pkg --debug -c ./pkg-angular.json -o sampler-editor-librarian-angular ./dist/main.js
      run: pkg --debug -c ./pkg-angular.json -o sampler-editor-librarian-angular ./dist/main.js
    - name: 'Upload Mac OS Angular Artifcat'
      uses: actions/upload-artifact@v4
      with:
        name: sampler-editor-librarian-angular-macos
        path: ./sampler-editor-librarian-angular-macos
    - name: Copy react ui type file to code base
      run: cp ./ui-type-react ./src/ui-type.ts
    - name: npm run build-release sampler-editor-librarian react
      run: npm run build-release
    - name: pkg --debug -c ./pkg-react.json -o sampler-editor-librarian-react ./dist/main.js
      run: pkg --debug -c ./pkg-react.json -o sampler-editor-librarian-react ./dist/main.js
    - name: 'Upload MAC OS React Artifcat'
      uses: actions/upload-artifact@v4
      with:
        name: sampler-editor-librarian-react-macos
        path: ./sampler-editor-librarian-react-macos
