name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd ./modules/sampler-editor-librarian-dto
    - run: npm ci
    - run: npm run build
    - run: cd ../sampler-editor-librarian-client
    - run: npm ci
    - run: npm run build
    - run: cd ../../
    - run: npm ci
    - run: npm run build
