name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libasound2-dev 
        version: 1.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm i
    - name: npm run build sampler-editor-librarian-dto
      working-directory: ./modules/sampler-editor-librarian-dto
      run: npm run build
    - name: npm i sampler-editor-librarian-client
      working-directory: ./modules/sampler-editor-librarian-client
      run: npm i
    - name: npm run build sampler-editor-librarian-client
      working-directory: ./modules/sampler-editor-librarian-client
      run: npm run build
    - run: npm i
    - run: npm run build
    - run: npm install -g pkg
    - run: pkg --debug -c ./package.json ./dist/main.js
    - name: 'Upload Artifcat'
      uses: actions/upload-artifact@v3
      with:
        name: sampler-editor-librarian-linux
        path: ./sampler-editor-librarian-linux
